services:
  - type: web
    name: loan-approval-api
    env: python
    plan: free
    buildCommand: "pip install -r python/API/requirements.txt"
    startCommand: "python python/API/FlaskApis.py"
    envVars:
      - key: FLASK_ENV
        value: development
      - key: PORT
        value: 10000