// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAXzWUk8r3A6aahw306lyxc1KnawYEKvI',
    appId: '1:305982064217:web:6754796f0ba37718395348',
    messagingSenderId: '305982064217',
    projectId: 'my-loan-application',
    authDomain: 'my-loan-application.firebaseapp.com',
    storageBucket: 'my-loan-application.firebasestorage.app',
    measurementId: 'G-85LHGBCL1C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuPPDYcxRyhVtSj39KE4WFuWxbCyg7tWU',
    appId: '1:305982064217:android:22aed515f0419169395348',
    messagingSenderId: '305982064217',
    projectId: 'my-loan-application',
    storageBucket: 'my-loan-application.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOOGTfntppCSyZjn0qTCjlP-0TOJCxoEo',
    appId: '1:305982064217:ios:669d480b447666cf395348',
    messagingSenderId: '305982064217',
    projectId: 'my-loan-application',
    storageBucket: 'my-loan-application.firebasestorage.app',
    iosBundleId: 'com.example.loanapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOOGTfntppCSyZjn0qTCjlP-0TOJCxoEo',
    appId: '1:305982064217:ios:669d480b447666cf395348',
    messagingSenderId: '305982064217',
    projectId: 'my-loan-application',
    storageBucket: 'my-loan-application.firebasestorage.app',
    iosBundleId: 'com.example.loanapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDAXzWUk8r3A6aahw306lyxc1KnawYEKvI',
    appId: '1:305982064217:web:cb642fbc2a2777b3395348',
    messagingSenderId: '305982064217',
    projectId: 'my-loan-application',
    authDomain: 'my-loan-application.firebaseapp.com',
    storageBucket: 'my-loan-application.firebasestorage.app',
    measurementId: 'G-H29STZWHXW',
  );
}
